// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XCNTWebServer.Models;

namespace XCNTWebServer.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    [Migration("20191002113818_setup")]
    partial class setup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XCNTWebServer.Models.Employee", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("First_Name")
                        .IsRequired();

                    b.Property<string>("Last_Name")
                        .IsRequired();

                    b.HasKey("UUID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("XCNTWebServer.Models.Expense", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<bool>("Approved");

                    b.Property<string>("Created_At")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("Description");

                    b.Property<string>("EmployeeUUID");

                    b.HasKey("UUID");

                    b.HasIndex("EmployeeUUID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("XCNTWebServer.Models.Expense", b =>
                {
                    b.HasOne("XCNTWebServer.Models.Employee", "Employee")
                        .WithMany("Expenses")
                        .HasForeignKey("EmployeeUUID")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
